const KEY = 'recall-room-state';
const COLORS = ['#c86c43', '#426c58', '#d29b47', '#768f9d', '#a8758b'];
const DAY = 86400000;
const seed = { theme: 'light', view: 'dashboard', selectedDeck: null, currentFolderId: null, studyMode: 'familiarize', stage: 'familiarize', gameMode: 'tap', streak: 0, activity: Array(14).fill(0), history: [], settings: { reminders: true, showAnswer: true }, account: null, folders: [], groups: [], decks: [
  { id: 'stoic', name: 'Stoic essentials', description: 'The ideas worth carrying with you.', color: '#c86c43', cards: [
    { id:'s1', front:'What is within my control?', back:'My judgments, choices, actions, and responses. Everything else is external.', reviews:2, dueAt:0 },
    { id:'s2', front:'“The happiness of your life depends upon the quality of your thoughts.”', back:'Marcus Aurelius, Meditations', reviews:1, dueAt:0 },
    { id:'s3', front:'What is the obstacle to the way?', back:'The obstacle is the way. An impediment to action advances action.', reviews:3, dueAt:Date.now()+DAY*2 }
  ]},
  { id:'french', name:'French in the wild', description:'Useful phrases for real conversations.', color: '#426c58', cards:[
    { id:'f1', front:'How do you say “I am looking for…”?', back:'Je cherche…', reviews:1, dueAt:0 },
    { id:'f2', front:'À tout à l’heure', back:'See you later (today)', reviews:0, dueAt:0 }
  ]},
  { id:'design', name:'Design principles', description:'A sharper eye, one principle at a time.', color:'#d29b47', cards:[
    { id:'d1', front:'What is the purpose of whitespace?', back:'To create hierarchy, rhythm, focus, and room for meaning to breathe.', reviews:4, dueAt:Date.now()+DAY*5 }
  ]}
]};
seed.decks = [];
let state = load();
let studyQueue = [];
let studyIndex = 0;
let revealed = false;
let gameState = { revealedWords: 0, slider: 100, answer: '', started: false, spoken: false, revealed: [], typed: [], blanks: [], scramble: [], choiceIndex: 0, choices: [], mistakes: 0, startedAt: 0 };
let gameStarted = false;
let resultState = null;

function load() { try { const saved = JSON.parse(localStorage.getItem(KEY)); return saved ? normalize(saved) : structuredClone(seed); } catch { return structuredClone(seed); } }
function normalize(saved) { const oldExampleIds=new Set(['stoic','french','design']); return { ...structuredClone(seed), ...saved, settings: { ...seed.settings, ...(saved.settings || {}) }, folders: Array.isArray(saved.folders) ? saved.folders : [], decks: (saved.decks || []).filter(deck=>!oldExampleIds.has(deck.id)).map(deck => ({ ...deck, folderId: deck.folderId || null, language: deck.language || 'English', body: deck.body || deck.cards?.map(card => `${card.front}\n${card.back}`).join('\n\n') || '', cards: (deck.cards || []).map(card => ({ ...card, dueAt: card.dueAt ?? (card.due > 0 ? Date.now() + card.due * DAY : 0), reviews: card.reviews || 0 })) })) }; }
function save() { localStorage.setItem(KEY, JSON.stringify(state)); }
function escapeHtml(value='') { return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function allCards() { return state.decks.flatMap(deck => deck.cards); }
function dueCards() { return allCards().filter(card => card.dueAt <= Date.now()); }
function formatDate() { return new Intl.DateTimeFormat('en', { month:'short', day:'numeric' }).format(new Date()); }
function showToast(message) { const el=document.querySelector('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2400); }
function setView(view) { state.view=view; save(); render(); window.scrollTo({top:0,behavior:'smooth'}); }
function deckById(id) { return state.decks.find(deck=>deck.id===id); }
function nav(title) { const folder=state.folders.find(item=>item.id===state.currentFolderId); document.querySelector('#breadcrumb').innerHTML = `${title} <span>/</span> ${escapeHtml(folder?.name || 'Your learning space')}`; document.querySelectorAll('.nav-item[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view)); document.querySelector('#deck-count').textContent=state.decks.length; document.querySelector('#due-count').textContent=dueCards().length; const profile=document.querySelector('#profile-label'); if(profile) profile.textContent=state.account?.name || 'Local workspace'; }
function render() { document.body.classList.toggle('practice-active',state.view==='study'); nav({dashboard:'Overview',library:'Library',study:'Study now',editor:'New collection',progress:'Progress',howto:'How it works',pricing:'Everything included',groups:'Groups',settings:'Settings'}[state.view] || 'Overview'); const root=document.querySelector('#app'); root.innerHTML = ({dashboard:dashboardView,library:libraryView,study:studyView,editor:editorView,progress:progressView,howto:howToView,pricing:pricingView,groups:groupsView,settings:settingsView}[state.view] || dashboardView)(); bind(); }

function dashboardView() {
  const due=dueCards().length, total=allCards().length, mastered=allCards().filter(c=>c.reviews>=3).length;
  return `<section class="view"><div class="page-heading"><div><div class="eyebrow">${formatDate()} · a quiet place to learn</div><h1>Make it yours,<br>by heart.</h1><p>Pick one small thing. Return to it often. Your memory gets stronger in the spaces between.</p></div><button class="primary-button" data-action="start-study">Start a study session ↗</button></div>
  <div class="stats-grid"><div class="stat-card"><div class="stat-label">Ready to review</div><div class="stat-number">${due}</div><div class="stat-note">cards waiting for you</div></div><div class="stat-card"><div class="stat-label">Cards learned</div><div class="stat-number">${mastered}</div><div class="stat-note">of ${total} total cards</div></div><div class="stat-card"><div class="stat-label">Collections</div><div class="stat-number">${state.decks.length}</div><div class="stat-note">ideas in orbit</div></div><div class="stat-card"><div class="stat-label">Current streak</div><div class="stat-number">${state.streak} <small style="font-size:15px">days</small></div><div class="stat-note">keep the thread going</div></div></div>
  <div class="dashboard-grid"><div><div class="section-heading"><h2>Your collections</h2><button class="text-button" data-view="library">See all →</button></div><div class="deck-list">${state.decks.slice(0,3).map(deckRow).join('') || empty('Nothing here yet. Create your first collection.', 'Create collection')}</div></div><div><div class="section-heading"><h2>Recent rhythm</h2><span class="eyebrow">last 14 days</span></div><div class="activity-panel"><div class="heatmap">${state.activity.map((n)=>`<div class="heat-col"><div class="heat-bar ${n?'active':''}" style="height:${Math.max(8,n*11)}px;opacity:${n ? .35+n/12 : .15}"></div></div>`).join('')}</div><div class="activity-footer"><span>14 days ago</span><span>today</span></div><div class="streak-line"><span class="streak-flame">⌁</span><span><strong>${state.streak} day rhythm</strong> · You showed up ${state.streak} days in a row.</span></div></div></div></div></section>`;
}
function deckRow(deck) { const mastered=deck.cards.filter(c=>c.reviews>=3).length; return `<div class="deck-row" data-deck="${deck.id}"><span class="deck-color" style="background:${deck.color}"></span><div class="deck-info"><strong>${escapeHtml(deck.name)}</strong><small>${deck.cards.length} cards · ${mastered} learned</small></div><div class="deck-progress"><div class="progress-track"><div class="progress-fill" style="width:${deck.cards.length ? mastered/deck.cards.length*100 : 0}%"></div></div><div class="progress-label">${deck.cards.length ? Math.round(mastered/deck.cards.length*100) : 0}%</div></div><span class="text-button">→</span></div>`; }
function libraryView() { const folder=state.folders.find(item=>item.id===state.currentFolderId); const folders=state.folders.filter(item=>(item.parentId || null)===state.currentFolderId); const decks=state.decks.filter(deck=>(deck.folderId || null)===state.currentFolderId); return `<section class="view"><div class="page-heading"><div><div class="eyebrow">${state.folders.length} folders · ${state.decks.length} memorisations</div><h1>${escapeHtml(folder?.name || 'Library')}</h1><p>Organise passages into folders and folders inside folders.</p></div><div class="page-actions"><button class="secondary-button" data-action="new-folder">＋ New folder</button><button class="primary-button" data-view="editor">＋ New memorisation</button></div></div><div class="library-toolbar"><input class="search-input" id="search" placeholder="Search this folder…" /><button class="secondary-button" id="export-btn">Export library ↓</button><button class="secondary-button" id="import-btn">Import ↑</button></div><div class="folder-path"><button class="text-button" data-folder="root">Library</button>${folderPath(folder?.parentId)}${folder ? `<span>/</span><strong>${escapeHtml(folder.name)}</strong>` : ''}</div><div class="library-grid" id="library-grid">${folders.map(folderCard).join('')}${decks.map(deckCard).join('')}${!folders.length&&!decks.length ? empty('This folder is empty. Add a folder or create your first memorisation.', 'New memorisation') : ''}</div></section>`; }
function folderPath(parentId) { const path=[]; let id=parentId; while(id) { const folder=state.folders.find(item=>item.id===id); if(!folder) break; path.unshift(`<span>/</span><button class="text-button" data-folder="${folder.id}">${escapeHtml(folder.name)}</button>`); id=folder.parentId; } return path.join(''); }
function folderCard(folder) { const children=state.folders.filter(item=>item.parentId===folder.id).length; const count=state.decks.filter(deck=>deck.folderId===folder.id).length; return `<button class="deck-card folder-card" data-folder="${folder.id}"><div class="folder-icon">▰</div><h3>${escapeHtml(folder.name)}</h3><p>${children} subfolders · ${count} memorisations</p><div class="deck-card-footer"><span>Open folder</span><span>→</span></div></button>`; }
function deckCard(deck) { const due=deck.cards.filter(c=>c.dueAt<=Date.now()).length; return `<div class="deck-card" data-deck="${deck.id}"><div class="deck-card-top"><span class="color-dot" style="background:${deck.color}"></span><span class="eyebrow">${due} due</span></div><h3>${escapeHtml(deck.name)}</h3><p>${escapeHtml(deck.description || 'A memorisation ready for practice.')}</p><div class="deck-card-footer"><span>${wordsFor(deck).length} words</span><span>${deck.cards.filter(c=>c.reviews>=3).length ? 'solid' : 'new'} →</span></div></div>`; }

function makeQueue() { const selected=state.selectedDeck ? deckById(state.selectedDeck) : null; if(selected) return [selected]; const dueIds=new Set(dueCards().map(card=>state.decks.find(deck=>deck.cards.some(item=>item.id===card.id))?.id)); return state.decks.filter(deck=>dueIds.has(deck.id)); }
function passageFor(deck) { return deck.body || deck.cards.map(card=>`${card.front} ${card.back}`).join(' '); }
function wordsFor(deck) { return passageFor(deck).trim().split(/\s+/).filter(Boolean); }
function currentPassage() { return studyQueue[studyIndex]; }
function resetGameState() { gameState={revealedWords:0,slider:100,answer:'',started:false,spoken:false,revealed:[],typed:[],blanks:[],scramble:[],choiceIndex:0,choices:[],mistakes:0,startedAt:Date.now()}; }
function normalizeWord(word) { return word.toLowerCase().replace(/[^\p{L}\p{N}'’-]/gu,''); }
function wordInput(word,index,kind='typed') { const values=gameState[kind] || []; return `<span class="word-input-wrap"><span class="word-hint">${escapeHtml(word[0] || '')}</span><input class="word-input" data-word-input="${index}" data-kind="${kind}" value="${escapeHtml(values[index] || '')}" autocomplete="off" spellcheck="false" aria-label="Word ${index+1}"></span>`; }
function renderWords(deck, mode) { const words=wordsFor(deck); if(mode==='first') return words.map(word => `${escapeHtml(word[0] || '')}${'_'.repeat(Math.max(2, word.length-1))}`).join(' '); if(mode==='blanks') return words.map((word,index) => index % 4 === 1 ? `<span class="blank-word">${' '.repeat(Math.max(3, word.length))}</span>` : escapeHtml(word)).join(' '); if(mode==='scramble') return [...words].sort(()=>Math.random()-.5).map(word=>`<button class="word-chip" data-word="${escapeHtml(word)}">${escapeHtml(word)}</button>`).join(''); return words.map(escapeHtml).join(' '); }
function gamePanel(deck) {
  const text=passageFor(deck), words=wordsFor(deck), mode=state.gameMode || 'tap';
  if(mode==='tap') { const visible=words.slice(0, gameState.revealedWords).join(' '); return `<div class="game-panel"><div class="passage-display ${visible?'':'is-hidden'}">${escapeHtml(visible || 'Tap to reveal the first phrase')}</div><input type="range" class="game-progress" min="0" max="${words.length}" value="${gameState.revealedWords}" data-reveal-slider><button class="primary-button" data-game-action="reveal-next">${gameState.revealedWords >= words.length ? 'Passage revealed' : 'Reveal next phrase'}</button><p class="game-note">Reveal the passage a little at a time while you build a mental map.</p></div>`; }
  if(mode==='slider') return `<div class="game-panel"><div class="unit-passage">${words.map((word,index)=>gameState.revealed.includes(index)?`<span>${escapeHtml(word)}</span>`:`<button class="masked-unit" data-reveal-word="${index}">${escapeHtml(word[0] || '•')}${'_'.repeat(Math.max(2,Math.min(8,word.length-1)))}</button>`).join(' ')}</div><label class="range-label">Support <strong>${Math.round((gameState.revealed.length/Math.max(words.length,1))*100)}%</strong></label><p class="game-note">Click a hidden unit or use the arrow keys to reveal the next word in order.</p><button class="secondary-button" data-game-action="complete">Finish attempt</button></div>`;
  if(mode==='listen') return `<div class="game-panel"><div class="passage-display">${escapeHtml(text)}</div><div class="game-actions"><button class="primary-button" data-game-action="speak-text">${gameState.started ? 'Play again' : 'Listen to passage'}</button><button class="secondary-button" data-game-action="complete">I followed along</button></div><p class="game-note">Use your browser's built-in voice to hear the passage.</p></div>`;
  if(mode==='first' || mode==='blanks') return `<div class="game-panel"><div class="passage-display recall-text word-input-grid">${words.map((word,index)=>mode==='first'?wordInput(word,index,'typed'):(index%4===1?wordInput(word,index,'blanks'):`<span class="visible-word">${escapeHtml(word)}</span>`)).join(' ')}</div><div class="game-actions"><button class="primary-button" data-game-action="check-words">Check recall</button><button class="secondary-button" data-game-action="show-answer">Show full passage</button></div>${gameState.started ? `<div class="answer-check">${escapeHtml(text)}</div><button class="primary-button" data-game-action="complete">I recalled it</button>` : ''}</div>`;
  if(mode==='scramble') return `<div class="game-panel"><p class="game-note">Tap words in the correct order. Mistakes stay visible so you can learn from them.</p><div class="scramble-zone" id="scramble-zone">${gameState.scramble.map(word=>`<button class="word-chip chosen" data-remove-word="${escapeHtml(word)}">${escapeHtml(word)}</button>`).join('')}</div><div class="word-bank">${[...words].sort((a,b)=>a.localeCompare(b)).filter(word=>!gameState.scramble.includes(word)).map(word=>`<button class="word-chip" data-word="${escapeHtml(word)}">${escapeHtml(word)}</button>`).join('')}</div><button class="secondary-button" data-game-action="show-answer">Show answer</button>${gameState.started ? `<button class="primary-button" data-game-action="complete">I got the order</button>` : ''}</div>`;
  if(mode==='type') return `<div class="game-panel"><p class="game-note">Type each word from memory. Press Space or Enter to move forward.</p><div class="passage-display recall-text word-input-grid">${words.map((word,index)=>wordInput(word,index,'typed')).join(' ')}</div><div class="game-actions"><button class="primary-button" data-game-action="check-words">Check recall</button><button class="secondary-button" data-game-action="show-answer">Show passage</button></div>${gameState.started ? `<div class="answer-check">${escapeHtml(text)}</div><button class="primary-button" data-game-action="complete">Mark this practice complete</button>` : ''}</div>`;
  if(mode==='run') return `<div class="game-panel"><div class="timer-readout">${gameState.startedAt ? '00:00' : 'Ready when you are'}</div><p class="game-note">Recite the entire passage continuously, like a real performance or audition run.</p><textarea class="game-textarea" id="game-answer" placeholder="Optional notes about your run…">${escapeHtml(gameState.answer)}</textarea><div class="game-actions"><button class="primary-button" data-game-action="check-answer">Finish run</button><button class="secondary-button" data-game-action="show-answer">Show passage</button></div>${gameState.started ? `<div class="answer-check">${escapeHtml(text)}</div><button class="primary-button" data-game-action="complete">Mark run complete</button>` : ''}</div>`;
  if(mode==='choice') { const index=gameState.choiceIndex || 0; const correct=words[index] || ''; if(!gameState.choices.length) gameState.choices=[correct,...words.filter((word,i)=>i!==index).sort(()=>Math.random()-.5).slice(0,5)].sort(()=>Math.random()-.5); return `<div class="game-panel"><p class="choice-progress">Choose the correct word <strong>${index+1} of ${words.length}</strong></p><div class="choice-context">${escapeHtml(words.slice(0,index).join(' '))} <span>_</span></div><div class="choice-grid">${gameState.choices.map(option=>`<button class="choice-button" data-choice="${escapeHtml(option)}">${escapeHtml(option)}</button>`).join('')}</div>${gameState.started ? `<div class="answer-check">The correct word was: ${escapeHtml(correct)}</div>` : ''}</div>`; }
  if(mode==='speak') return `<div class="game-panel"><div class="passage-display reference-line">${gameState.spoken ? 'Listening for your recitation…' : 'Press start, then recite the passage aloud.'}</div><button class="primary-button" data-game-action="speech">${gameState.spoken ? 'Stop listening' : 'Start speech check'}</button>${gameState.started ? `<div class="answer-check">Speech recognition is complete. Compare your phrasing with the passage.</div><button class="primary-button" data-game-action="complete">Mark as recalled</button>` : ''}</div>`;
  return '';
}
function gameName() { return ({tap:'Tap to Reveal',slider:'Slider',listen:'Listen',first:'First Letter',blanks:'Blanks',scramble:'Scramble',type:'Type It',choice:'Multiple Choice',speak:'Speak',run:'Run Scene'})[state.gameMode || 'tap']; }
function gameSetup(deck) { const mode=state.gameMode || 'tap'; const copy={tap:'Reveal the passage a little at a time and let your brain anticipate what comes next.',slider:'Adjust support gradually, then recall the missing words in order.',listen:'Hear the text read aloud and follow its rhythm with your eyes and voice.',first:'Use the first letter of each word as a thin clue for active recall.',blanks:'Fill the strategic gaps and use feedback to strengthen weak spots.',scramble:'Put the passage back in order by rebuilding its phrases.',type:'Type the passage from memory with no help.',choice:'Rebuild the passage one word at a time with no skips.',speak:'Recite the passage aloud and compare your attempt.',run:'Perform one continuous run-through, like a real audition or speech.'}; const settings=mode==='tap'?'<div class="setup-options"><span>Reveal by</span><button class="setup-option active">Phrase</button><button class="setup-option">Word</button><button class="setup-option">Sentence</button></div>':mode==='slider'?'<div class="setup-options"><span>Game mode</span><button class="setup-option active">Progression</button><button class="setup-option">Fade</button></div>':mode==='choice'?'<div class="setup-options"><span>Difficulty</span><button class="setup-option">Easy</button><button class="setup-option">Medium</button><button class="setup-option active">Hard</button></div>':''; return `<div class="game-setup"><div class="setup-icon">${mode==='tap'?'☝':mode==='listen'?'◉':mode==='type'?'T':'✦'}</div><p class="eyebrow">${escapeHtml(gameName())}</p><h2>${escapeHtml(gameName())}</h2>${settings}<div class="setup-help">${escapeHtml(copy[mode])}</div><button class="primary-button setup-start" data-game-action="start-game">Start <span>→</span></button></div>`; }
function resultView(deck) { const score=resultState?.score || 0; const rating=resultState?.rating ?? 0; return `<div class="game-result"><div class="result-icon">${score>=75?'✓':'↻'}</div><p class="eyebrow">${escapeHtml(gameName())}</p><h2>${score>=75?'Practice complete':'Needs more practice'}</h2><p>${score>=75?'Great job reviewing the text. Keep reviewing while it is fresh.':'Review the passage with an easier game, then try this one again.'}</p><div class="result-stats"><div><strong>${score}%</strong><small>Mastery score</small></div><div><strong>${resultState?.mistakes || 0}</strong><small>Mistakes</small></div><div><strong>+${rating>=2?5:3}</strong><small>Points earned</small></div></div><div class="result-actions"><button class="primary-button" data-result="again">Play again</button><button class="secondary-button" data-result="games">Back to games</button></div></div>`; }
function studyView() {
  if (!studyQueue.length) { studyQueue=makeQueue(); studyIndex=0; resetGameState(); gameStarted=false; resultState=null; }
  const deck=currentPassage();
  if(!deck) return `<section class="view"><div class="study-wrap"><div class="empty"><p>You’re all caught up. Add a new memorization or come back when your next review is due.</p><button class="primary-button" data-view="library">Browse your library</button></div></div></section>`;
  const games=[['tap','Tap to Reveal','Guided exposure'],['slider','Slider','Fade support'],['listen','Listen','Hear the passage'],['first','First Letter','Recall with initials'],['blanks','Blanks','Fill the gaps'],['scramble','Scramble','Restore the order'],['type','Type It','Active recall'],['choice','Multiple Choice','Choose the phrase'],['speak','Speak','Recite aloud'],['run','Run Scene','One continuous run']];
  const body=resultState ? resultView(deck) : (gameStarted ? gamePanel(deck) : gameSetup(deck));
  const ratings=gameStarted&&!resultState ? `<div class="rating-actions practice-rating"><button class="rating-button" data-rating="0"><strong>Needs work</strong><small>Review soon</small></button><button class="rating-button" data-rating="1"><strong>Getting there</strong><small>Tomorrow</small></button><button class="rating-button" data-rating="2"><strong>Solid</strong><small>In 3 days</small></button><button class="rating-button" data-rating="3"><strong>Nailed it</strong><small>In a week</small></button></div>` : '';
  const groups=[['familiarize','Familiarize','Learn it',['tap','slider','listen']],['solidify','Solidify','Practice it',['first','blanks','scramble']],['evaluate','Evaluate','Test it',['type','choice','speak','run']]];
  return `<section class="view"><div class="study-wrap wide-study"><div class="practice-topline"><button class="text-button" data-view="library">← Back to memorisations</button><div class="practice-title"><span class="eyebrow">${escapeHtml(gameName())}</span><strong>${escapeHtml(deck.name)}</strong></div><div class="practice-icons"><button class="icon-button" title="Instructions">?</button><button class="icon-button" title="Restart" data-game-action="restart">↻</button></div></div><div class="study-header"><div><div class="eyebrow">${escapeHtml(deck.language || 'English')}</div><h1>${escapeHtml(gameName())}</h1><p class="study-subtitle">${escapeHtml(deck.description || 'Practice this memorization in small, deliberate steps.')}</p></div><div class="study-count">${studyIndex+1} / ${studyQueue.length}</div></div><div class="stage-board">${groups.map(group=>`<section class="stage-column ${group[0]}"><div class="stage-column-heading"><div><span class="stage-number">${group[0]==='familiarize'?'1':group[0]==='solidify'?'2':'3'}</span><h2>${group[1]}</h2></div><small>${group[2]}</small></div>${games.filter(game=>group[3].includes(game[0])).map(game=>`<button class="game-card ${state.gameMode===game[0]?'active':''}" data-stage="${group[0]}" data-game="${game[0]}"><strong>${game[1]}</strong><small>${game[2]}</small><span class="game-progress-dot"></span></button>`).join('')}</section>`).join('')}</div>${body}${ratings}</div></section>`;
}
function editorView() { return `<section class="view"><div class="page-heading"><div><div class="eyebrow">Create a memorization</div><h1>Bring it by heart.</h1><p>Paste a speech, scripture, poem, song, script, or study note. The practice loop will shape itself around the passage.</p></div></div><div class="editor-layout"><form class="form-panel" id="deck-form"><h2>Memorization details</h2><div class="form-field"><label for="deck-name">Title</label><input class="form-input" id="deck-name" required placeholder="e.g. The Road Not Taken" /></div><div class="form-field"><label for="deck-language">Language</label><input class="form-input" id="deck-language" value="English" placeholder="English" /></div><div class="form-field"><label for="deck-description">Short description</label><input class="form-input" id="deck-description" placeholder="What is this passage for?" /></div><div class="form-field"><label for="deck-color">Accent color</label><select class="form-select" id="deck-color">${COLORS.map(c=>`<option value="${c}">${c}</option>`).join('')}</select></div><div class="form-field"><label for="deck-body">Passage</label><textarea class="form-textarea passage-input" id="deck-body" required placeholder="Paste the full text here…"></textarea></div><div class="form-actions"><button class="primary-button">Create memorization</button><button type="button" class="secondary-button" data-view="library">Cancel</button></div></form><div class="card-preview"><div class="eyebrow">Practice loop</div><h3>Familiarize → Solidify → Evaluate</h3><div class="preview-answer">Your passage stays yours, locally in this browser. You can export it whenever you want.</div></div></div></section>`; }
function progressView() { const cards=allCards(), learned=cards.filter(c=>c.reviews>=3).length, reviews=state.history.length, max=Math.max(...state.activity,1); return `<section class="view"><div class="page-heading"><div><div class="eyebrow">Your practice, made visible</div><h1>Progress</h1><p>Small repetitions compound. Here is the shape of your learning habit.</p></div></div><div class="progress-panel"><div class="progress-chart"><h2>Reviews over time</h2><div class="bar-chart">${state.activity.map((n,i)=>`<div style="height:${Math.max(5,n/max*100)}%"><span>${i===13?'today':i+1}</span></div>`).join('')}</div></div><div class="insight-panel"><h2>At a glance</h2><div class="insight"><div><strong>${reviews}</strong><small>Total reviews</small></div><span class="eyebrow">all time</span></div><div class="insight"><div><strong>${learned}/${cards.length}</strong><small>Cards learned</small></div><span class="eyebrow">mastery</span></div><div class="insight"><div><strong>${state.streak} days</strong><small>Current streak</small></div><span class="eyebrow">rhythm</span></div></div></div></section>`; }
function howToView() { const stages=[['1','Familiarize','Learn it','Absorb the shape of the passage through exposure and listening.','Tap to Reveal · Slider · Listen'],['2','Solidify','Practice it','Work for recall with gaps, initials, and scrambled order.','First Letter · Blanks · Scramble'],['3','Evaluate','Test it','Remove support and discover what you can truly recall.','Type It · Multiple Choice · Speak · Run Scene']]; return `<section class="view method-view"><div class="method-hero"><div class="eyebrow">The method</div><h1>Why this actually works</h1><p>Reading something over and over is not enough. Recall Room turns memorisation into a sequence of small, purposeful challenges.</p><button class="primary-button" data-view="editor">Start memorising →</button></div><div class="method-intro"><div class="eyebrow">The framework</div><h2>Three phases of memorisation</h2><p>Every game belongs to one of three phases. Move through them in order to build recall that lasts.</p></div><div class="phase-list">${stages.map(stage=>`<article class="phase-row"><div class="phase-marker">${stage[0]}</div><div><div class="eyebrow">Step ${stage[0]} · ${stage[1]}</div><h2>${stage[2]}</h2><p>${stage[3]}</p><strong>${stage[4]}</strong></div></article>`).join('')}</div><div class="review-method"><div class="eyebrow">Built-in review schedule</div><h2>Smart review, not more review</h2><p>Successful practice grows the interval. Struggling brings the passage back sooner.</p><div class="review-steps">${[['1 day','Just learned'],['3 days','Getting familiar'],['1 week','Solidifying'],['2 weeks','Long-term memory'],['1 month','Mastered']].map(step=>`<div><strong>${step[0]}</strong><small>${step[1]}</small></div>`).join('')}</div></div></section>`; }
function pricingView() { const features=['Unlimited memorisations','Nested folders','All 10 practice games','Dynamic spaced repetition','Text-to-speech and speech check','Import and export','Progress and mastery analytics','Local account profile']; return `<section class="view included-view"><div class="method-hero"><div class="eyebrow">Everything included</div><h1>Memorise more, freely.</h1><p>No premium tier, locked game, or artificial limit. Every feature in this app is available in the local workspace.</p><button class="primary-button" data-view="editor">Add a memorisation →</button></div><div class="included-card"><div><div class="eyebrow">Recall Room</div><h2>Always free</h2><p>Built for GitHub Pages and your own browser storage.</p></div><ul>${features.map(feature=>`<li>✓ ${feature}</li>`).join('')}</ul><button class="secondary-button" data-action="account">Manage local account</button></div></section>`; }
function groupsView() { return `<section class="view"><div class="page-heading"><div><div class="eyebrow">Practice together</div><h1>Groups</h1><p>Create a small learning circle, share a memorisation code, and keep each other accountable.</p></div><button class="primary-button" data-action="new-group">＋ Create group</button></div><div class="group-grid">${state.groups.length ? state.groups.map(group=>`<div class="group-card"><div class="group-avatar">${escapeHtml(group.name[0])}</div><h2>${escapeHtml(group.name)}</h2><p>${group.members || 1} members · ${group.code}</p><button class="secondary-button" data-copy-code="${group.code}">Copy invite code</button></div>`).join('') : empty('No groups yet. Create one for a study circle or join with an invite code.', 'Create group')}</div></section>`; }
function settingsView() { return `<section class="view"><div class="page-heading"><div><div class="eyebrow">Your preferences</div><h1>Settings</h1><p>A few quiet controls for making this space feel like yours.</p></div></div><div class="settings-list"><div class="setting-row"><div><h3>Daily reminder</h3><p>Keep a gentle nudge to return to your cards.</p></div><button class="toggle ${state.settings.reminders?'on':''}" data-setting="reminders"><span></span></button></div><div class="setting-row"><div><h3>Show answer on reveal</h3><p>Keep answers visible while rating a card.</p></div><button class="toggle ${state.settings.showAnswer?'on':''}" data-setting="showAnswer"><span></span></button></div><div class="setting-row"><div><h3>Export your data</h3><p>Your library stays in this browser. Take a copy anytime.</p></div><button class="secondary-button" id="export-btn">Download JSON ↓</button></div><div class="setting-row"><div><h3>Start fresh</h3><p>Remove your local library and restore the example collections.</p></div><button class="secondary-button" id="reset-btn">Reset library</button></div></div></section>`; }
function empty(text, label) { return `<div class="empty"><p>${text}</p><button class="secondary-button" data-view="editor">${label}</button></div>`; }

function bind() {
  document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>{ studyQueue=[]; setView(el.dataset.view); }));
  document.querySelectorAll('[data-folder]').forEach(el=>el.addEventListener('click',()=>{ state.currentFolderId=el.dataset.folder==='root'?null:el.dataset.folder; setView('library'); }));
  document.querySelector('[data-action="new-folder"]')?.addEventListener('click',showFolderModal);
  document.querySelectorAll('[data-deck]').forEach(el=>el.addEventListener('click',()=>{ state.selectedDeck=el.dataset.deck; studyQueue=[]; setView('study'); }));
  document.querySelector('[data-action="start-study"]')?.addEventListener('click',()=>{ state.selectedDeck=null; studyQueue=[]; setView('study'); }); document.querySelector('[data-action="reveal"]')?.addEventListener('click',()=>{ revealed=true; render(); }); document.querySelectorAll('[data-rating]').forEach(el=>el.addEventListener('click',()=>rate(Number(el.dataset.rating))));
  document.querySelectorAll('[data-stage]').forEach(el=>el.addEventListener('click',()=>{ state.stage=el.dataset.stage; state.gameMode={familiarize:'tap',solidify:'first',evaluate:'type'}[state.stage]; gameStarted=false; resultState=null; resetGameState(); render(); }));
  document.querySelectorAll('[data-game]').forEach(el=>el.addEventListener('click',()=>{ state.gameMode=el.dataset.game; gameStarted=false; resultState=null; resetGameState(); render(); }));
  document.querySelector('[data-game-action="start-game"]')?.addEventListener('click',()=>{ gameStarted=true; resetGameState(); render(); });
  document.querySelector('[data-game-action="restart"]')?.addEventListener('click',()=>{ gameStarted=false; resultState=null; resetGameState(); render(); });
  document.querySelector('[data-result="again"]')?.addEventListener('click',()=>{ resultState=null; gameStarted=false; resetGameState(); render(); }); document.querySelector('[data-result="games"]')?.addEventListener('click',()=>{ resultState=null; gameStarted=false; render(); });
  document.querySelector('[data-game-action="reveal-next"]')?.addEventListener('click',()=>{ gameState.revealedWords=Math.min(wordsFor(currentPassage()).length,gameState.revealedWords+Math.max(3,Math.ceil(wordsFor(currentPassage()).length/5))); render(); });
  document.querySelector('[data-reveal-slider]')?.addEventListener('input',e=>{ gameState.revealedWords=Number(e.target.value); render(); }); document.querySelector('[data-opacity-slider]')?.addEventListener('input',e=>{ gameState.slider=Number(e.target.value); e.target.previousElementSibling.style.opacity=Math.max(.12,gameState.slider/100); e.target.previousElementSibling.previousElementSibling.textContent=`Text visibility ${gameState.slider}%`; });
  document.querySelectorAll('[data-reveal-word]').forEach(el=>el.addEventListener('click',()=>{ const index=Number(el.dataset.revealWord); if(!gameState.revealed.includes(index)) gameState.revealed.push(index); render(); }));
  document.querySelectorAll('[data-word-input]').forEach(el=>el.addEventListener('input',e=>{ const kind=e.target.dataset.kind; gameState[kind][Number(e.target.dataset.wordInput)]=e.target.value; }));
  document.querySelector('[data-game-action="check-words"]')?.addEventListener('click',()=>{ const deck=currentPassage(), words=wordsFor(deck), values=gameState.gameMode==='blanks'?gameState.blanks:gameState.typed; const indexes=gameState.gameMode==='blanks'?words.map((_,i)=>i%4===1?i:-1).filter(i=>i>=0):words.map((_,i)=>i); const misses=indexes.filter(i=>normalizeWord(values[i]||'')!==normalizeWord(words[i])).length; gameState.mistakes+=misses; gameState.started=true; render(); });
  document.querySelector('[data-game-action="show-answer"]')?.addEventListener('click',()=>{ gameState.started=true; render(); }); document.querySelector('[data-game-action="complete"]')?.addEventListener('click',()=>{ gameState.started=true; showToast('Practice marked complete. Rate your recall below.'); render(); });
  document.querySelector('[data-game-action="speak-text"]')?.addEventListener('click',()=>{ if('speechSynthesis' in window) { speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(passageFor(currentPassage()))); gameState.started=true; render(); } else showToast('Text-to-speech is not available in this browser'); });
  document.querySelector('[data-game-action="check-answer"]')?.addEventListener('click',()=>{ gameState.answer=document.querySelector('#game-answer').value; gameState.started=true; render(); }); document.querySelector('[data-game-action="speech"]')?.addEventListener('click',startSpeechCheck);
  document.querySelectorAll('[data-choice]').forEach(el=>el.addEventListener('click',()=>{ const words=wordsFor(currentPassage()), correct=words[gameState.choiceIndex||0]; if(el.dataset.choice===correct) { gameState.choiceIndex++; gameState.choices=[]; if(gameState.choiceIndex>=words.length) gameState.started=true; render(); } else { gameState.mistakes++; el.disabled=true; showToast('Not quite. Try another choice.'); } }));
  document.querySelectorAll('[data-word]').forEach(el=>el.addEventListener('click',()=>{ gameState.scramble.push(el.dataset.word); if(gameState.scramble[gameState.scramble.length-1]!==wordsFor(currentPassage())[gameState.scramble.length-1]) gameState.mistakes++; render(); })); document.querySelectorAll('[data-remove-word]').forEach(el=>el.addEventListener('click',()=>{ gameState.scramble=gameState.scramble.filter((_,index)=>index!==gameState.scramble.indexOf(el.dataset.removeWord)); render(); }));
  document.querySelector('#import-btn')?.addEventListener('click',()=>document.querySelector('#file-input').click()); document.querySelector('#import-nav')?.addEventListener('click',()=>document.querySelector('#file-input').click()); document.querySelector('#export-btn')?.addEventListener('click',exportData);
  document.querySelector('#reset-btn')?.addEventListener('click',()=>{ if(confirm('Remove all local memorisations and folders?')) { state=structuredClone(seed); save(); render(); showToast('Library cleared'); } }); document.querySelector('#search')?.addEventListener('input', e=>{ const q=e.target.value.toLowerCase(); document.querySelector('#library-grid').innerHTML=state.decks.filter(d=>(d.folderId||null)===state.currentFolderId && (d.name+' '+d.description+' '+d.body).toLowerCase().includes(q)).map(deckCard).join('')+`<button class="deck-card new-card" data-view="editor"><div><span>＋</span><strong>New memorisation</strong></div></button>`; bind(); });
  document.querySelector('#deck-form')?.addEventListener('submit', createDeck); document.querySelectorAll('[data-setting]').forEach(el=>el.addEventListener('click',()=>{ const setting=el.dataset.setting; state.settings[setting]=!state.settings[setting]; save(); render(); })); document.querySelector('#game-answer')?.addEventListener('input',e=>{ gameState.answer=e.target.value; });
  document.querySelector('#account-button')?.addEventListener('click',showAccount);
  document.querySelector('[data-action="account"]')?.addEventListener('click',showAccount);
  document.querySelector('[data-action="new-group"]')?.addEventListener('click',showGroupModal); document.querySelectorAll('[data-copy-code]').forEach(el=>el.addEventListener('click',()=>{ navigator.clipboard?.writeText(el.dataset.copyCode); showToast(`Invite code ${el.dataset.copyCode} copied`); }));
}
function addCardField() { const wrapper=document.createElement('div'); wrapper.className='card-field'; wrapper.innerHTML='<div class="form-field"><label>Prompt</label><textarea class="form-textarea card-front" required placeholder="Another prompt"></textarea></div><div class="form-field"><label>Answer</label><textarea class="form-textarea card-back" required placeholder="Another answer"></textarea></div>'; document.querySelector('#card-fields').appendChild(wrapper); wrapper.querySelectorAll('textarea').forEach(el=>el.addEventListener('input',updatePreview)); }
function updatePreview() { document.querySelector('#preview-front').textContent=document.querySelector('.card-front')?.value || 'Your first prompt will appear here.'; document.querySelector('#preview-back').textContent=document.querySelector('.card-back')?.value || 'And the answer will sit right below it.'; }
function createDeck(e) { e.preventDefault(); const body=document.querySelector('#deck-body').value.trim(); const name=document.querySelector('#deck-name').value.trim(); const deck={id:'deck-'+Date.now(), folderId:state.currentFolderId, name, language:document.querySelector('#deck-language').value.trim() || 'English', description:document.querySelector('#deck-description').value.trim(), body, color:document.querySelector('#deck-color').value, cards:[{id:'card-'+Date.now(),front:name,back:body,reviews:0,dueAt:0}]}; state.decks.unshift(deck); save(); showToast('Memorization created'); setView('library'); }
function rate(rating) { const deck=studyQueue[studyIndex]; const source=deck.cards[0]; const intervals=[0,1,3,7]; source.reviews += rating>=2 ? 1 : 0; source.dueAt = rating===0 ? 0 : Date.now()+intervals[rating]*DAY; state.history.push({date:Date.now(),rating,game:state.gameMode,mistakes:gameState.mistakes}); state.history=state.history.slice(-100); state.activity[state.activity.length-1]=(state.activity[state.activity.length-1]||0)+1; state.streak=Math.max(1,state.streak+1); const base=rating===3?100:rating===2?82:rating===1?55:18; const score=Math.max(0,Math.round(base-(gameState.mistakes*4))); resultState={score,rating,mistakes:gameState.mistakes}; save(); render(); }
function exportData() { const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='recall-room-library.json'; a.click(); URL.revokeObjectURL(url); showToast('Library exported'); }
function startSpeechCheck() { const Recognition=window.SpeechRecognition || window.webkitSpeechRecognition; if(!Recognition) { showToast('Speech recognition is not available in this browser'); return; } const recognition=new Recognition(); recognition.lang=(currentPassage().language || 'en-US').split('-')[0]; recognition.interimResults=false; recognition.onresult=()=>{ gameState.spoken=true; gameState.started=true; render(); }; recognition.onerror=()=>showToast('We could not hear that attempt'); recognition.start(); gameState.spoken=true; render(); }
function showFolderModal() { document.querySelector('#modal-root').innerHTML='<div class="modal-backdrop" data-close-modal><div class="modal"><h2>New folder</h2><p>Create it here, or make it the first layer of a deeper organisation system.</p><form id="folder-form"><div class="form-field"><label for="folder-name">Folder name</label><input class="form-input" id="folder-name" required placeholder="e.g. Speeches or Scripture" /></div><div class="form-actions"><button class="primary-button">Create folder</button><button type="button" class="secondary-button" data-close-modal>Cancel</button></div></form></div></div>'; document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',e=>{ if(e.target===el) document.querySelector('#modal-root').innerHTML=''; })); document.querySelector('#folder-form').addEventListener('submit',e=>{ e.preventDefault(); const name=document.querySelector('#folder-name').value.trim(); state.folders.push({id:`folder-${Date.now()}`,name,parentId:state.currentFolderId}); save(); document.querySelector('#modal-root').innerHTML=''; render(); showToast('Folder created'); }); }
function showGroupModal() { document.querySelector('#modal-root').innerHTML='<div class="modal-backdrop" data-close-modal><div class="modal"><h2>Create a group</h2><p>Groups are stored locally in this free static workspace. Share the invite code with your study circle.</p><form id="group-form"><div class="form-field"><label for="group-name">Group name</label><input class="form-input" id="group-name" required placeholder="e.g. Sunday study circle" /></div><div class="form-actions"><button class="primary-button">Create group</button><button type="button" class="secondary-button" data-close-modal>Cancel</button></div></form></div></div>'; document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',e=>{ if(e.target===el) document.querySelector('#modal-root').innerHTML=''; })); document.querySelector('#group-form').addEventListener('submit',e=>{ e.preventDefault(); const name=document.querySelector('#group-name').value.trim(); state.groups.push({id:`group-${Date.now()}`,name,code:Math.random().toString(36).slice(2,8).toUpperCase(),members:1}); save(); document.querySelector('#modal-root').innerHTML=''; render(); showToast('Group created'); }); }
function showAccount() { const account=state.account; document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop" data-close-modal><div class="modal account-modal"><h2>${account ? `Welcome back, ${escapeHtml(account.name)}` : 'Sign in to Recall Room'}</h2><p>Your memorisations are currently stored locally in this browser. Signing in can identify your workspace, but cloud sync needs a configured authentication provider.</p>${account ? `<div class="account-summary"><strong>${escapeHtml(account.name)}</strong><span>${escapeHtml(account.email)}</span></div><button class="secondary-button" id="sign-out">Sign out</button>` : `<form id="local-account-form"><div class="form-field"><label for="account-name">Name</label><input class="form-input" id="account-name" required placeholder="Your name" /></div><div class="form-field"><label for="account-email">Email</label><input class="form-input" id="account-email" type="email" required placeholder="you@example.com" /></div><button class="primary-button">Continue with local account</button></form><div class="auth-divider">or</div><button class="secondary-button" id="google-auth">Continue with Google</button><small class="auth-note">Google OAuth is provider-ready, but requires Firebase, Supabase, or another OAuth project before it can be connected to a static GitHub Pages site.</small>`}</div></div>`; document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',e=>{ if(e.target===el) document.querySelector('#modal-root').innerHTML=''; })); document.querySelector('#local-account-form')?.addEventListener('submit',e=>{ e.preventDefault(); state.account={name:document.querySelector('#account-name').value.trim(),email:document.querySelector('#account-email').value.trim()}; save(); document.querySelector('#modal-root').innerHTML=''; render(); showToast('Account saved on this device'); }); document.querySelector('#sign-out')?.addEventListener('click',()=>{ state.account=null; save(); document.querySelector('#modal-root').innerHTML=''; render(); }); document.querySelector('#google-auth')?.addEventListener('click',()=>showToast('Connect a Google OAuth project to enable this provider')); }
function showHelp() { document.querySelector('#modal-root').innerHTML='<div class="modal-backdrop" data-close-modal><div class="modal"><h2>Recall Room shortcuts</h2><p>Keep your hands on the keyboard during a study session.</p><div class="shortcut-list"><div><span>Reveal answer</span><kbd>Space</kbd></div><div><span>Rate a card</span><kbd>1 2 3 4</kbd></div><div><span>Close this window</span><kbd>Esc</kbd></div></div><button class="primary-button" data-close-modal>Got it</button></div></div>'; document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',e=>{ if(e.target===el) document.querySelector('#modal-root').innerHTML=''; })); }
document.querySelector('#theme-toggle').addEventListener('click',()=>{ document.documentElement.classList.toggle('dark'); state.theme=document.documentElement.classList.contains('dark')?'dark':'light'; save(); }); document.querySelector('#help-button').addEventListener('click',showHelp);
document.addEventListener('keydown',e=>{ if(e.key==='Escape') document.querySelector('#modal-root').innerHTML=''; if(state.view==='study' && e.target.tagName!=='INPUT' && e.target.tagName!=='TEXTAREA') { if(e.code==='Space'){ e.preventDefault(); if(!revealed){ revealed=true; render(); } } const rating=Number(e.key)-1; if(revealed && rating>=0 && rating<=3) rate(rating); } });
document.querySelector('#file-input').addEventListener('change', async e=>{ const file=e.target.files[0]; if(!file)return; try { const text=await file.text(); if(file.name.toLowerCase().endsWith('.json')) { const imported=JSON.parse(text); if(!Array.isArray(imported.decks)) throw Error(); state=normalize({...state,...imported}); } else { const cards=text.split(/\n\s*\n|\n(?=Q\s*[:\-])/i).map(block=>block.trim()).filter(Boolean).map((block,index)=>{ const parts=block.split(/\n?A\s*[:\-]|\n?::\s*/i); return {id:`imported-${Date.now()}-${index}`,front:parts[0].replace(/^Q\s*[:\-]\s*/i,'').trim(),back:(parts[1]||'Add an answer').trim(),reviews:0,dueAt:0}; }); if(!cards.length) throw Error(); state.decks.unshift({id:`imported-${Date.now()}`,name:file.name.replace(/\.[^.]+$/,''),description:'Imported notes',color:COLORS[0],cards}); } save(); render(); showToast('Library imported'); } catch { showToast('Could not read that file'); } e.target.value=''; });
if(state.theme==='dark') document.documentElement.classList.add('dark');
render();
